<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StafifyDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seed company profiles
        DB::table('company_profiles')->insert([
            [
                'company_id' => 1,
                'company_name' => 'Stafify',
                'company_address' => 'Greenwoods Park, 2F, Lot 17, Parcel 4, Rizal Hwy, CBD Area, Subic Bay Freeport Zone, 2200 Zambales',
                'company_phone' => '(047) 603 0032',
                'company_email' => 'stafify@gmail.com',
                'company_logo' => 'default-company-logo.png',
                'timezone' => 'Asia/Manila',
                'week_start' => 1,
                'year_type' => 'fiscal',
                'fiscal_start_month' => 1,
                'fiscal_start_day' => 18,
                'fiscal_end_month' => 12,
                'fiscal_end_day' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'company_name' => 'CompanyTest153',
                'company_address' => '23',
                'company_phone' => '12345',
                'company_email' => 'test153@gmail.com',
                'company_logo' => 'default-company-logo.png',
                'timezone' => 'UTC',
                'week_start' => 0,
                'year_type' => 'calendar',
                'fiscal_start_month' => null,
                'fiscal_start_day' => null,
                'fiscal_end_month' => null,
                'fiscal_end_day' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Seed company branches
        DB::table('company_branches')->insert([
            [
                'branch_id' => 1,
                'company_id' => 1,
                'branch_location' => 'Headquarters',
                'branch_address' => 'Greenwoods Park, 2F, Lot 17, Parcel 4, Rizal Hwy, CBD Area, Subic Bay Freeport Zone, 2200 Zambales',
                'branch_phone' => '(047) 603 0032',
                'is_headquarters' => true,
                'created_at' => '2025-04-24 07:27:34',
                'updated_at' => '2025-04-24 07:27:34',
            ],
            [
                'branch_id' => 2,
                'company_id' => 1,
                'branch_location' => 'BGC Office',
                'branch_address' => 'Unit 88, High Street, Bonifacio Global City, Taguig City, Philippines',
                'branch_phone' => '+639177022610',
                'is_headquarters' => false,
                'created_at' => '2025-05-04 08:58:17',
                'updated_at' => '2025-05-04 08:58:17',
            ],
            [
                'branch_id' => 3,
                'company_id' => 2,
                'branch_location' => 'Headquarters',
                'branch_address' => '23',
                'branch_phone' => '12345',
                'is_headquarters' => true,
                'created_at' => '2025-10-06 11:22:55',
                'updated_at' => '2025-10-06 11:22:55',
            ]
        ]);

        // Seed departments
        DB::table('stafify_departments')->insert([
            ['department_id' => 1, 'department_name' => 'Management'],
            ['department_id' => 2, 'department_name' => 'IT Department'],
            ['department_id' => 3, 'department_name' => 'Sales'],
        ]);

        // Seed positions
        DB::table('stafify_positions')->insert([
            ['position_id' => 1, 'position_name' => 'CEO'],
            ['position_id' => 2, 'position_name' => 'Developer'],
            ['position_id' => 3, 'position_name' => 'Project Manager'],
            ['position_id' => 4, 'position_name' => 'Relationship Manager'],
        ]);

        // Seed stafify users
        DB::table('stafify_users')->insert([
            [
                'user_id' => 2,
                'user_name' => 'allenlim',
                'full_name' => 'Allen Lim',
                'user_email' => 'stafify@gmail.com',
                'phone_number' => '09164933599',
                'user_pin' => 924,
                'company' => 'Stafify',
                'user_dept' => 'Management',
                'user_position' => 'CEO',
                'access_level' => 2,
                'is_admin' => 1,
                'address' => 'Greenwoods Park, 2F, Lot 17, Parcel 4, Rizal Hwy, CBD Area, Subic Bay Freeport Zone, 2200 Zambales',
                'country' => 'Philippines',
                'country_code' => '',
                'employment_date' => '1990-09-24',
                'branch_location' => 'Headquarters',
                'engagement_status' => 'full_time',
                'user_status' => 'engaged',
                'user_type' => 'isp',
                'wage_type' => 'non_mwe',
                'sil_status' => 1,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'user_name' => 'siahbautista',
                'full_name' => 'Siah Bautista',
                'user_email' => 'bautistamahasiah@gmail.com',
                'phone_number' => '09684382598',
                'user_pin' => 90602,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Project Manager',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '#9 Aguinaldo St. New Asinan Olongapo City, Zambales',
                'country' => 'Philippines',
                'country_code' => 'PH',
                'employment_date' => '2025-02-10',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'user_name' => 'aaorcs',
                'full_name' => 'Andrea Anne Orca',
                'user_email' => 'annedreaorca@gmail.com',
                'phone_number' => '09984092760',
                'user_pin' => 102703,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '163-D Lower Kalaklan Olongapo City',
                'country' => 'Philippines',
                'country_code' => 'PH',
                'employment_date' => '2025-02-10',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'user_name' => 'cjaycuya',
                'full_name' => 'Christian Jay Cuya',
                'user_email' => 'cjapaycuya16@gmail.com',
                'phone_number' => '09763498472',
                'user_pin' => 51603,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Full-Stack Developer',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '22 Rizal St. Brgy. Barretto, Olongapo City',
                'country' => 'Philippines',
                'country_code' => 'PH',
                'employment_date' => '2025-02-10',
                'branch_location' => 'Headquarters',
                'engagement_status' => 'full_time',
                'user_status' => 'active',
                'user_type' => 'employee',
                'wage_type' => 'mwe',
                'sil_status' => 1,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'user_name' => 'chaws',
                'full_name' => 'Charles John Malit',
                'user_email' => 'charlesjohnmalit4@gmail.com',
                'phone_number' => '',
                'user_pin' => 0,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Payroll',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '',
                'country' => 'Philippines',
                'country_code' => 'PH',
                'employment_date' => '2025-02-24',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'user_name' => 'marielle',
                'full_name' => 'Marielle Corpuz',
                'user_email' => 'mariellecorpuz02@gmail.com',
                'phone_number' => '09397263021',
                'user_pin' => 0,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => 'Baloy Long Beach Rd., Brgy. Barretto, Olongapo City, Zambales, 2200',
                'country' => 'Philippines',
                'country_code' => '',
                'employment_date' => '2025-02-25',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'user_name' => 'jambe',
                'full_name' => 'Jay-vee Ubaldo',
                'user_email' => 'jayveeubaldo110@gmail.com',
                'phone_number' => '09983666903',
                'user_pin' => 0,
                'company' => 'Stafify',
                'user_dept' => 'HRIS',
                'user_position' => 'Talent Acquisition',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => 'Blk 21 santol St.',
                'country' => 'Philippines',
                'country_code' => '',
                'employment_date' => '2025-02-24',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'user_name' => 'renz',
                'full_name' => 'John Laurenze Leguidleguid',
                'user_email' => 'Johnlaurenzel@gmail.com',
                'phone_number' => '09273227055',
                'user_pin' => 0,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => 'Blk 23 Ubas Street Gordon Heights Olongapo City',
                'country' => 'Philippines',
                'country_code' => 'PH',
                'employment_date' => '2025-02-24',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 11,
                'user_name' => 'gabriel',
                'full_name' => 'John Gabriel Orbeta',
                'user_email' => 'gabrielorbeta11@gmail.com',
                'phone_number' => '09665915026',
                'user_pin' => 0,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => 'purok 4 banaba st. brgy barretto.',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2025-02-24',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 14,
                'user_name' => 'tintin21',
                'full_name' => 'Justine Dimalanta',
                'user_email' => 'dimalantajustine8@gmail.com',
                'phone_number' => '',
                'user_pin' => 0,
                'company' => 'Stafify',
                'user_dept' => 'AFIS',
                'user_position' => 'Project Manager',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2025-02-24',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 15,
                'user_name' => 'Aulwen',
                'full_name' => 'Aulwen Dizon',
                'user_email' => 'aulwen126@gmail.com',
                'phone_number' => '09650636585',
                'user_pin' => 0,
                'company' => 'Stafify',
                'user_dept' => 'Sales',
                'user_position' => 'Relationship Manager',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '#50 18th Street East Bajac-Bajac, Olongapo City',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2025-04-16',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 16,
                'user_name' => 'Karu',
                'full_name' => 'Carl Barrera',
                'user_email' => '202011828@gordoncollege.edu.ph',
                'phone_number' => '+639468291705',
                'user_pin' => 30801,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '#8 - 21st Place West Bajac - Bajac, Olongapo City',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2025-03-07',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 17,
                'user_name' => 'Lanpher Garcia',
                'full_name' => 'Lanpher Garcia',
                'user_email' => 'garcia.lanpher13@gmail.com',
                'phone_number' => '+63 956 618 2903',
                'user_pin' => 41103,
                'company' => 'Stafify',
                'user_dept' => 'Unassigned',
                'user_position' => 'Unassigned',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '31 14th Street, East Tapinac, Olongapo city',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2025-03-10',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 19,
                'user_name' => 'amilmusa',
                'full_name' => 'Amil Musa',
                'user_email' => 'amilmusa03@gmail.com',
                'phone_number' => '09198119666',
                'user_pin' => 406,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => '20 fontaine East Bajac Bajac Olongapo City',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2025-04-23',
                'branch_location' => 'Headquarters',
                'engagement_status' => 'full_time',
                'user_status' => 'active',
                'user_type' => 'isp',
                'wage_type' => 'mwe',
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 24,
                'user_name' => 'alsheretteramos',
                'full_name' => 'Alsherette Ramos',
                'user_email' => 'alsheretteramos@gmail.com',
                'phone_number' => '09647691126',
                'user_pin' => 1234,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 2,
                'is_admin' => 0,
                'address' => 'Olongapo City',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2025-02-24',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 26,
                'user_name' => 'test2',
                'full_name' => 'test',
                'user_email' => 'tes@gmail.com',
                'phone_number' => '123456789',
                'user_pin' => 123456,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 3,
                'is_admin' => 0,
                'address' => '123 Anyway street',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2003-05-05',
                'branch_location' => 'Headquarters',
                'engagement_status' => null,
                'user_status' => null,
                'user_type' => null,
                'wage_type' => null,
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 27,
                'user_name' => 'basicuser',
                'full_name' => 'Basic User',
                'user_email' => 'basicuser@gmail.com',
                'phone_number' => '01234567890',
                'user_pin' => 123456,
                'company' => 'Stafify',
                'user_dept' => 'IT Department',
                'user_position' => 'Developer',
                'access_level' => 3,
                'is_admin' => 0,
                'address' => '123 Anyway street',
                'country' => '',
                'country_code' => '',
                'employment_date' => '2025-05-05',
                'branch_location' => 'Headquarters',
                'engagement_status' => 'full_time',
                'user_status' => 'active',
                'user_type' => 'isp',
                'wage_type' => 'govt_services',
                'sil_status' => 0,
                'statutory_benefits' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Seed user rates
        DB::table('stafify_user_rates')->insert([
            [
                'rate_id' => 1,
                'user_id' => 3,
                'hourly_rate' => 150.00,
                'daily_rate' => 1200.00,
                'monthly_rate' => 26400.00,
                'created_at' => '2025-08-15 09:21:17',
                'updated_at' => '2025-08-15 09:21:17',
            ]
        ]);

        // Seed settings
        DB::table('stafify_settings')->insert([
            [
                'setting_id' => 1,
                'setting_key' => 'early_clock_in_minutes',
                'setting_value' => '15',
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'setting_id' => 2,
                'setting_key' => 'on_time_late_minutes',
                'setting_value' => '5',
                'updated_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Seed payroll settings
        DB::table('payroll_settings')->insert([
            [
                'id' => 1,
                'company_id' => 1,
                'frequency' => 2,
                'disbursement' => 1,
                'deduction_schedule' => 'weekly',
                'benefits_url' => 'https://docs.google.com/spreadsheets/d/1l3n2bxlc3SUx-zlhN6VfwLQgyBWM2q6ccFBntWu5dkU/edit?gid=0#gid=0',
                'created_at' => now(),
                'updated_at' => '2025-10-09 07:20:27',
            ]
        ]);

        // Seed payrolls
        DB::table('stafify_payrolls')->insert([
            ['id' => '1rQ08O3zw6vAXzrsP3SNyt1Vk-ByKlfYo', 'template_id' => '13FWVbkg9VVuL4ZimN8istUAGPfdHOcxe', 'name' => 'ISP'],
            ['id' => '1tKGME3ZLE1ajLX0AY8zSoNoIhx-xc0M9', 'template_id' => '12sQe2DN_GMIxHEMBjahhGNGd0OomNFf5', 'name' => 'EE'],
            ['id' => '1rQkUqepDGHCFVW0R05KB_j-OPkAkaSCb', 'template_id' => '1XX7y4asO3_o45ACzon5wI1xfQ86DTcYR', 'name' => 'Hybrid'],
        ]);

        // Seed sales toolkit
        DB::table('sales_toolkit')->insert([
            [
                'sales_id' => 1,
                'user_id' => 2,
                'sales_title' => 'Withholding Tax Table',
                'form_url' => '',
                'response_url' => 'https://docs.google.com/spreadsheets/d/1jnz_eMobmVgGYMCAnamhdxZ4GTQIO1yfBeVYV8WmQ3E/edit?gid=0#gid=0',
                'icon' => 'Write.gif',
                'type' => 'Sheet',
                'is_approved' => 1,
                'created_at' => '2025-08-18 12:57:39',
                'updated_at' => '2025-08-18 13:04:39',
            ],
            [
                'sales_id' => 2,
                'user_id' => 2,
                'sales_title' => 'Benefits and Tax Table',
                'form_url' => '',
                'response_url' => 'https://docs.google.com/spreadsheets/d/1ZCBUSXqKLLVGq2TETu7rKVavjoDszXfS-bW2Zk69tEU/edit?usp=sharing',
                'icon' => 'Write.gif',
                'type' => 'Sheet',
                'is_approved' => 1,
                'created_at' => '2025-08-18 13:02:28',
                'updated_at' => '2025-08-18 13:04:41',
            ],
            [
                'sales_id' => 7,
                'user_id' => 2,
                'sales_title' => 'SSS Website',
                'form_url' => 'https://www.sss.gov.ph/',
                'response_url' => '',
                'icon' => 'Globe.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 02:41:34',
                'updated_at' => '2025-10-09 02:55:28',
            ],
            [
                'sales_id' => 8,
                'user_id' => 2,
                'sales_title' => 'Philhealth Website',
                'form_url' => 'https://www.philhealth.gov.ph/',
                'response_url' => '',
                'icon' => 'Globe.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 02:59:10',
                'updated_at' => '2025-10-09 02:59:51',
            ],
            [
                'sales_id' => 10,
                'user_id' => 2,
                'sales_title' => 'Pag-IBIG Website',
                'form_url' => 'https://www.pagibigfund.gov.ph/',
                'response_url' => '',
                'icon' => 'Cart.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 03:04:14',
                'updated_at' => '2025-10-09 05:09:44',
            ],
            [
                'sales_id' => 11,
                'user_id' => 2,
                'sales_title' => 'BIR Excel Uploader',
                'form_url' => 'https://bir-excel-uploader.com/',
                'response_url' => '',
                'icon' => 'Globe.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 05:01:58',
                'updated_at' => '2025-10-09 05:09:46',
            ],
            [
                'sales_id' => 12,
                'user_id' => 2,
                'sales_title' => 'BIR ORUS',
                'form_url' => 'https://orus.bir.gov.ph/home',
                'response_url' => '',
                'icon' => 'Register.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 05:03:36',
                'updated_at' => '2025-10-09 05:09:49',
            ],
            [
                'sales_id' => 13,
                'user_id' => 2,
                'sales_title' => 'BIR eFPS',
                'form_url' => 'https://efps.bir.gov.ph/',
                'response_url' => '',
                'icon' => 'Write.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 05:05:21',
                'updated_at' => '2025-10-09 05:09:51',
            ],
            [
                'sales_id' => 14,
                'user_id' => 2,
                'sales_title' => 'BIR ePAY',
                'form_url' => 'https://www.bir.gov.ph/ePay',
                'response_url' => '',
                'icon' => 'Settlement.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 05:06:30',
                'updated_at' => '2025-10-09 05:09:53',
            ],
            [
                'sales_id' => 15,
                'user_id' => 2,
                'sales_title' => 'BIR eAFS',
                'form_url' => 'https://eafs.bir.gov.ph/eafs/',
                'response_url' => '',
                'icon' => 'Request.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 05:07:50',
                'updated_at' => '2025-10-09 05:09:55',
            ],
            [
                'sales_id' => 16,
                'user_id' => 2,
                'sales_title' => 'BIR Downloadables',
                'form_url' => 'https://www.bir.gov.ph/Downloadables',
                'response_url' => '',
                'icon' => 'Folder.gif',
                'type' => 'Website',
                'is_approved' => 1,
                'created_at' => '2025-10-09 05:09:06',
                'updated_at' => '2025-10-09 05:09:56',
            ]
        ]);
    }
}